const actionTypes = {
  START_GET_ROI_DATA: 'START_GET_ROI_DATA',
  SUCCESS_GET_ROI_DATA: 'SUCCESS_GET_ROI_DATA',
  FAIL_GET_ROI_DATA: 'FAIL_GET_ROI_DATA',
  CLEAR_DATA: 'CLEAR_DATA',
  START_GET_SUBJECT: 'START_GET_SUBJECT',
  SUCCESS_GET_SUBJECT: 'SUCCESS_GET_SUBJECT'
}

export default actionTypes
