const actionTypes = {
  GETTING_LOADING_START: 'GETTING_LOADING_START',
  GETTING_LOADING_SUCCESS: 'GETTING_LOADING_SUCCESS',
  GETTING_LOADING_FAIL: 'GETTING_LOADING_FAIL',
  CLEAR_DATA: 'CLEAR_DATA',
  SET_PAGE: 'SET_PAGE'
}

export default actionTypes
